# Generated by Django 2.2.5 on 2020-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('PIUMEDELVENTO', 'Le Piume del Vento'), ('AMICIDELTEATRO', 'Gli Amici del Teatro')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
