# Generated by Django 2.2.5 on 2020-02-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200209_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
