# Generated by Django 2.2.5 on 2020-02-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200209_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('PIUMEDELVENTO', 'Le Piume del Vento'), ('AMICIDELTEATRO', 'Gli Amici del Teatro')], max_length=100),
        ),
    ]
