# Generated by Django 2.2.5 on 2020-02-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='titolo',
        ),
    ]
