# Generated by Django 2.2.5 on 2020-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallery_titolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageslist',
            name='descrizione',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='imageslist',
            name='titolo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
