# Generated by Django 2.2.5 on 2020-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200215_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
