# Generated by Django 2.2.5 on 2020-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='ImagesList',
        ),
    ]
